### ISSUE TITLE
web端登录不了

### ISSUE THREAD

**Issue by ovarte** [leochen-g/wechaty-web-panel#1]
web端登录不了么，大佬

**Comment by leochen-g** [comment]
可以登录的，现在用的是UOS的桌面版协议，不能直接登录web版也可以用的
具体可以看这里，还有 [重磅：绕过登录限制，wechaty免费版web协议重放荣光](https://wechaty.js.org/2021/04/13/wechaty-uos-web/)
#https://github.com/wechaty/wechaty-puppet-wechat/issues/127

**Comment by leochen-g** [comment]
#https://github.com/wechaty/wechaty-puppet-wechat/issues/127
