### ISSUE TITLE
登陆跑出异常

### ISSUE THREAD

**Issue by DDDDDDDOU** [leochen-g/wechaty-web-panel#5]
<img width="614" alt="image" src="https://user-images.githubusercontent.com/48237560/158958225-151aa57b-6bce-4409-b17d-1475c7a46549.png">

test程序异常如下

<img width="1013" alt="image" src="https://user-images.githubusercontent.com/48237560/158958307-95886dad-04fa-4ea2-9c75-aa0a0dfb3690.png">

**Comment by leochen-g** [comment]
拉取最新代码，确认微信已经实名认证
