### ISSUE TITLE
运行项目出错

### ISSUE THREAD

**Issue by yandisky** [leochen-g/wechaty-web-panel#7]
执行 npm install wechaty-web-panel@latest wechaty@latest --save
再运行 node mybot.js 出现下面问题
![image](https://user-images.githubusercontent.com/72863175/182784991-1dde8b1b-cab3-4662-94a7-e1d8f5818cd7.png)

**Comment by leochen-g** [comment]
please use this project to run wechaty-web-panel   https://github.com/leochen-g/wechat-assistant-pro
