### ISSUE TITLE
这个智能微秘书 从注册到登录都有很多BUG问题。

### ISSUE THREAD

**Issue by fcoolish** [leochen-g/wechaty-web-panel#8]
注册、微信直接登录都有bug

**Comment by leochen-g** [comment]
欢迎提出问题

**Comment by fcoolish** [comment]
> 欢迎提出问题

用字母的qq邮箱注册不了，只能数字的。然后微信扫码登录是报错不能登录

**Comment by leochen-g** [comment]
> > 欢迎提出问题
> 
> 用字母的qq邮箱注册不了，只能数字的。然后微信扫码登录是报错不能登录

1、带字母的qq邮件无法收件问题确实存在，很多情况是被退件了，你可以百度看一下，带字母的qq邮箱退件率很高，不是平台问题。建议用数字qq邮箱
2、微信扫码属于辅助手段，目前正在排查问题中，后续会增加github登录功能
